language: ruby
rvm:
  - 2.1.1
cache:
  - bundler
  - apt
branches:
  only:
    - master
    - develop
notifications:
  hipchat: 83906daf46b0ce558ce21f13353861@246078
  on_success: always
  on_failure: always
script:
  - bundle exec rspec
addons:
  code_climate:
    repo_token: 2a61bdd24e056cb4b413988835cbaca74c293838117a21da8a6258b36ec485e9
